### ISSUE TITLE
Webpack fails to run

### ISSUE THREAD

**Issue by ronag** [js-next/react-style#49]
I'm using the latest react-style revision and following the web pack example. However, when I try to run web pack with the dev server I get the following errors.

error:
```
[22:52:08] [webpack-dev-server] http://localhost:8080/webpack-dev-server/index.html

/web/node_modules/webpack/lib/Compilation.js:429
		throw new Error("Cannot rebuild a complex module with variables or blocks");
		      ^
Error: Cannot rebuild a complex module with variables or blocks
    at Tapable.Compilation.rebuildModule (/web/node_modules/webpack/lib/Compilation.js:429:9)
    at async.forEach.contents.push.chunk (/web/node_modules/extract-text-webpack-plugin/index.js:108:20)
    at /web/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/web/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/web/node_modules/extract-text-webpack-plugin/node_modules/async/lib/async.js:110:9)
    at Tapable.<anonymous> (/node_modules/extract-text-webpack-plugin/index.js:102:11)
```

webpack.config.js
```
var webpack           = require('webpack');
var path              = require('path');
var ReactStylePlugin  = require('react-style-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: [
    './client/client'
  ],
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js',
    publicPath: '/build/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new ReactStylePlugin('bundle.css')
  ],
  resolve: {
    extensions: ['', '.js', '.jsx', '.styl']
  },
  module: {
    loaders: [
      {
        test: /\.jsx$/,   
        loaders: [
          'react-hot',
          ReactStylePlugin.loader(),
          'jsx?harmony&insertPragma=React.DOM'
        ]
      }, 
      {
        test: /\.css?$/,  
        loader:  ExtractTextPlugin.extract('css-loader')
      },
      {
        test: /\.(otf|eot|svg|ttf|woff)/,
        loader: 'url-loader?limit=8192'
      }
    ]
  }
};
```
package.json
```
{
  "devDependencies": {
    "css-loader": "^0.8.0",
    "flux": "^2.0.1",
    "gulp": "^3.8.8",
    "gulp-jscs": "^1.1.2",
    "gulp-jshint": "^1.8.4",
    "gulp-nodemon": "^1.0.4",
    "gulp-react": "^1.0.1",
    "gulp-util": "^3.0.1",
    "jshint-stylish": "^0.4.0",
    "jsx-loader": "^0.11.0",
    "react": "^0.11.1",
    "react-hot-loader": "^0.4.3",
    "react-style": "git+https://github.com/js-next/react-style.git",
    "react-style-webpack-plugin": "git+https://github.com/js-next/react-style-webpack-plugin.git",
    "webpack": "^1.4.0-beta3",
    "webpack-dev-server": "^1.4.10",
    "url-loader": "^0.5.5"
  }
}
```

**Comment by SanderSpies** [comment]
Too old.
