### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by ronag** [js-next/react-style#79]
Trying to move back to webpack version.... without much success. Not sure what is going on.

```javascript
ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~
/react-style-webpack-plugin/lib/entry.js!(webpack)-dev-server/client?http://localhost:8080
Module build failed: ReferenceError: document is not defined
  at Object.eval (<anonymous>:3:22)
  at Object.eval (<anonymous>:71:30)
  at Object.<anonymous> (D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Boffins\Auto
mation\web2\node_modules\webpack-dev-server\client\index.js?http://localhost:8080:505:2)
  at __webpack_require__ (D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Boffins\Aut
omation\web2\node_modules\webpack-dev-server\client\index.js?http://localhost:8080:473:30)
  at D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Foo\web\node_mod
ules\webpack-dev-server\client\index.js?http://localhost:8080:498:37
  at Object.<anonymous> (D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Boffins\Auto
mation\web2\node_modules\webpack-dev-server\client\index.js?http://localhost:8080:501:10)
  at Module._compile (module.js:456:26)
  at Object.loaderContext.exec (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModu
leMixin.js:86:7)
  at Object.<anonymous> (D:\Foo\web\node_modules\extract-text-webpack-plugin\loader.js:93:22)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compiler.js:210:10)
  at D:\Foo\web\node_modules\webpack\lib\Compiler.js:397:12
  at Tapable.next (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:11)
  at Object.<anonymous> (D:\Foo\web\node_modules\extract-text-webpack-plugin\loader.js:77:5)
  at Tapable.next (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:37)
  at CachePlugin.<anonymous> (D:\Foo\web\node_modules\webpack\lib\CachePlugin.js:40:4)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:73:1
3)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compiler.js:394:9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:529:13)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:524:10)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:519:9)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:515:8)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.seal (D:\Foo\web\node_modules\webpack\lib\Compilation.js:481:7)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compiler.js:391:15)
  at D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:107:11
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:415:10)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:388:12)
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at Object.async.each (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:121:20)
  at Tapable.Compilation.addModuleDependencies (D:\Foo\web\node_modules\webpack\lib\Compilation.js:168:8
)
  at Tapable.Compilation.processModuleDependencies (D:\Foo\web\node_modules\webpack\lib\Compilation.js:1
56:7)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:298:11)
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:112:4
  at Array.forEach (native)
  at callback (D:\Foo\web\node_modules\webpack\lib\Compilation.js:111:12)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:128:10)
  at DependenciesBlock.<anonymous> (D:\Foo\web\node_modules\webpack\lib\NormalModule.js:97:10)
  at DependenciesBlock.onModuleBuild (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\Norm
alModuleMixin.js:283:10)
  at nextLoader (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:253:
25)
  at D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:270:15
  at Object.context.callback (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModule
Mixin.js:146:14)
  at Object.module.exports (D:\Foo\web\node_modules\jsx-loader\index.js:25:8)

ERROR in ./~/react-style-webpack-plugin/lib/emptyLoader.js!./~/extract-text-webpack-plugin/loader.js?{"remove":true}!./~
/react-style-webpack-plugin/lib/entry.js!(webpack)/hot/only-dev-server.js
Module build failed: ReferenceError: window is not defined
  at Object.eval (<anonymous>:64:25)
  at Object.<anonymous> (D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Boffins\Auto
mation\web2\node_modules\jsx-loader\index.js?harmony!D:\Foo\web\node_modules\webpack\hot\only-dev-server
.js:505:2)
  at __webpack_require__ (D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Boffins\Aut
omation\web2\node_modules\jsx-loader\index.js?harmony!D:\Foo\web\node_modules\webpack\hot\only-dev-serve
r.js:473:30)
  at D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Foo\web\node_mod
ules\jsx-loader\index.js?harmony!D:\Foo\web\node_modules\webpack\hot\only-dev-server.js:498:37
  at Object.<anonymous> (D:\Foo\web\node_modules\react-style-webpack-plugin\lib\entry.js!D:\Boffins\Auto
mation\web2\node_modules\jsx-loader\index.js?harmony!D:\Foo\web\node_modules\webpack\hot\only-dev-server
.js:501:10)
  at Module._compile (module.js:456:26)
  at Object.loaderContext.exec (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModu
leMixin.js:86:7)
  at Object.<anonymous> (D:\Foo\web\node_modules\extract-text-webpack-plugin\loader.js:93:22)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compiler.js:210:10)
  at D:\Foo\web\node_modules\webpack\lib\Compiler.js:397:12
  at Tapable.next (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:69:11)
  at Object.<anonymous> (D:\Foo\web\node_modules\extract-text-webpack-plugin\loader.js:77:5)
  at Tapable.next (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:71:37)
  at CachePlugin.<anonymous> (D:\Foo\web\node_modules\webpack\lib\CachePlugin.js:40:4)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:73:1
3)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compiler.js:394:9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:529:13)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:524:10)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:519:9)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:515:8)
  at Tapable.applyPluginsAsync (D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:60:6
9)
  at Tapable.seal (D:\Foo\web\node_modules\webpack\lib\Compilation.js:481:7)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compiler.js:391:15)
  at D:\Foo\web\node_modules\webpack\node_modules\tapable\lib\Tapable.js:107:11
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:415:10)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:388:12)
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at done (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:135:19)
  at D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:32:16
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:310:10
  at Object.async.each (D:\Foo\web\node_modules\webpack\node_modules\async\lib\async.js:121:20)
  at Tapable.Compilation.addModuleDependencies (D:\Foo\web\node_modules\webpack\lib\Compilation.js:168:8
)
  at Tapable.Compilation.processModuleDependencies (D:\Foo\web\node_modules\webpack\lib\Compilation.js:1
56:7)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:298:11)
  at D:\Foo\web\node_modules\webpack\lib\Compilation.js:112:4
  at Array.forEach (native)
  at callback (D:\Foo\web\node_modules\webpack\lib\Compilation.js:111:12)
  at Tapable.<anonymous> (D:\Foo\web\node_modules\webpack\lib\Compilation.js:128:10)
  at DependenciesBlock.<anonymous> (D:\Foo\web\node_modules\webpack\lib\NormalModule.js:97:10)
  at DependenciesBlock.onModuleBuild (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\Norm
alModuleMixin.js:283:10)
  at nextLoader (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:253:
25)
  at D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:270:15
  at Object.context.callback (D:\Foo\web\node_modules\webpack\node_modules\webpack-core\lib\NormalModule
Mixin.js:146:14)
  at Object.module.exports (D:\Foo\web\node_modules\jsx-loader\index.js:25:8)
```

webpack.config.js
```javascript
var webpack          = require('webpack');
var path             = require('path');
var ReactStylePlugin = require('react-style-webpack-plugin');

module.exports = {
  entry: [
    './client/client'
  ],
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js',
    publicPath: '/build/'
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new ReactStylePlugin('bundle.css')
  ],
  resolve: {
    extensions: ['', '.js'],
    alias: {
      'react-style$': require.resolve('react-style/lib')
    }
  },
  module: {
    loaders: [
      { test: /\.worker\.js$/, loader: 'worker' },
      { 
        test: /\.js$/, 
        loaders: [
          'react-hot',
          ReactStylePlugin.loader(),
          'jsx?harmony'
        ] 
      },
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.(otf|eot|svg|ttf|woff)/, loader: 'url' },
      { test: /\.png/, loader: 'file' },
    ]
  }
};
```

**Comment by SanderSpies** [comment]
See 0.4.0 for an example with React Hot Loader :-). There is more react-hot-loader work coming up for 0.5.0 - stay tuned!

**Comment by matthewwithanm** [comment]
Sorry, I'm confused…

Is the react-hot example working? Its package.json points to a branch or tag that no longer exists, and it seems to have a bunch of issues using master. If I use master with a config like the example's in my own project, a full page refresh occurs on every change. If I try to use the ReactStylePlugin (as @ronag above), I get the same error about document not being defined when the plugin attempts to run the code in the dev server.

Apologies if this is the wrong place to ask. I just can't seem to figure out the current state of react-styles + HMR.

**Comment by SanderSpies** [comment]
@matthewwithanm - it should work if you use "react-style" : "^0.4.1" - inline styles only btw.
